export const infirmaries = [
  { label: "Enfermaria 01", value: 1 },
  { label: "Enfermaria 02", value: 2 },
  { label: "Enfermaria 03", value: 3 },
  { label: "Enfermaria 04", value: 4 },
];

export const hospitalBeds = [
  { label: "Leito 01", value: 1 },
  { label: "Leito 02", value: 2 },
  { label: "Leito 03", value: 3 },
  { label: "Leito 04", value: 4 },
  { label: "Leito 05", value: 5 },
  { label: "Leito 333", value: 6 },
  { label: "Leito 1234", value: 7 },
  { label: "Leito 34344", value: 8 },
  { label: "Leito 4444", value: 9 },
  { label: "Leito 00", value: 10 },
  { label: "Leito 01", value: 11 },
  { label: "Leito 02", value: 12 },
];

export const patients = [
  { name: "Ana Beatriz Maria Eduarda" },
  { name: "Ana Cecília Maria Fernanda" },
  { name: "Ana Clara Maria Flor" },
  { name: "Ana Júlia Maria Helena" },
  { name: "Ana Laura Maria Isis" },
  { name: "Ana Lívia Maria Júlia" },
  { name: "Ana Luiza Maria Laura" },
  { name: "Ana Sofia Maria Luiza" },
  { name: "Ana Vitória Maria Sophia" },
  { name: "Maria Alice Maria Valentina" },
  { name: "Maria Cecília Maria Vitória" },
  { name: "Maria Clara " },
  { name: "Maria Ribeiro da Costa e Lima" },
];

export const physicalExam = [
  {
    id: 1,
    value: "Condições gerais",
    isSelected: false,
    part: 1,
    options: [
      { id: "Bom", description: "Bom" },
      { id: "Regular", description: "Regular" },
      { id: "Grave", description: "Grave" },
      { id: "Muito grave", description: "Muito grave" },
    ],
    comment: "",
  },
  { id: 2, value: "Estado mental", isSelected: false, part: 1 },
  { id: 3, value: "Pele", isSelected: false, part: 1 },
  { id: 4, value: "Cabelo", isSelected: false, part: 1 },
  { id: 5, value: "Cabeça", isSelected: false, part: 1 },
  { id: 6, value: "Olhos", isSelected: false, part: 1 },
  { id: 7, value: "Ouvidos", isSelected: false, part: 1 },
  { id: 8, value: "Nariz e seios nasais", isSelected: false, part: 1 },
  { id: 9, value: "Boca e garganta", isSelected: false, part: 1 },
  { id: 10, value: "Pescoço", isSelected: false, part: 1 },
  { id: 11, value: "Mamas", isSelected: false, part: 1 },
  { id: 12, value: "Axilas", isSelected: false, part: 1 },
  { id: 13, value: "Sistema respiratório", isSelected: false, part: 2 },
  { id: 14, value: "sistema cardiovascular", isSelected: false, part: 2 },
  { id: 15, value: "Sistema vascular periférico", isSelected: false, part: 2 },
  { id: 16, value: "Sistema gastrointestinal", isSelected: false, part: 2 },
  { id: 17, value: "Sistema urinário", isSelected: false, part: 2 },
  {
    id: 18,
    value: "Sistema gincológico/obstétrico",
    isSelected: false,
    part: 2,
  },
  { id: 19, value: "Saúde sexual", isSelected: false, part: 2 },
  { id: 20, value: "Sistema musculoesquelético", isSelected: false, part: 2 },
  { id: 21, value: "Sistema neurológico", isSelected: false, part: 2 },
  { id: 22, value: "Sistema hematológico", isSelected: false, part: 2 },
  { id: 23, value: "Sistema endócrino", isSelected: false, part: 2 },
  { id: 24, value: "Autocuidado", isSelected: false, part: 2 },
];
